import Head from 'next/head'
import { ChangeEvent, useContext, useEffect, useReducer, useState } from 'react';
import { auth } from '../firebase'
import { onAuthStateChanged, signOut, User } from "firebase/auth";
// import UserContext from './userContext'

import Calendar from "react-calendar";
import 'react-calendar/dist/Calendar.css';

import { observer } from "mobx-react-lite"


import styles from '../styles/Home.module.css'
import Dailies from './dailies';
import Login from '../components/login';
import { DateContext } from '../store/date';
import Splash from '../components/splash';


interface HomeProps {
  user: User
}

export default observer(function Home(props: HomeProps) {

  // const [date, setDate] = useState(new Date())
  const {date, setDate} = useContext(DateContext)
  const [user, setUser] = useState(props.user)

  useEffect(() => {
    const unsubsc = onAuthStateChanged(auth, user => {
      if (user) {
        setUser(user)
      }
    })

    return unsubsc
  }, [])
  
  return (
      <div className={styles.container}>
        <Head>
          <title>Dailies</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <Splash /> 
          {/* <h1 className={styles.title}>
            <Splash /> 
            Welcome to <span className={styles.name}>Dailies!</span>
          </h1> */}

          {user ? (
            <>
              <p className={styles.description}>
                <span className={styles.name}>{user.displayName}</span>, Choose a date to see your Dailies
              </p>
              <button className={`btn ${styles.signOut}`} onClick={async () => {
                await signOut(auth)
                setUser(props.user)
              }}>Sign out</button>

              <Calendar onChange={setDate} value={date} />

              <Dailies date={date} user={user} />
            </>
          ) : (
            <Login />
          )}
        </main>

        <footer className={styles.footer}>
          <a
            href="https://hasan-sh.github.io/portfolio"
            target="_blank"
            rel="noopener noreferrer"
          >
            Build by{' '}
            <span className={styles.logo}>Hasan Sh</span>
          </a>
        </footer>
      </div>
  )
})

export async function getStaticProps() {
  return {
    props: {
      user: auth.currentUser
    }, // will be passed to the page component as props
  }
}